In [1]:
import torch
import torch.nn as nn

torch.manual_seed(0)  # 재현용

vocab_size = 10   # 단어 10개라고 가정
embed_dim = 4     # 각 단어를 4차원 벡터로

embedding = nn.Embedding(vocab_size, embed_dim)

# 단어 인덱스 몇 개 넣어보기 (예: 1번, 5번, 3번 단어)
idx = torch.tensor([1, 5, 3])
vectors = embedding(idx)
print(vectors)
print(vectors.shape)   # 어떤 모양이 나올까? 직접 예측해보고 확인

tensor([[ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [ 0.1198,  1.2377,  1.1168, -0.2473]], grad_fn=<EmbeddingBackward0>)
torch.Size([3, 4])


In [2]:
print(embedding.weight)            # 10 x 4 행렬 전체
print(embedding.weight[1])         # 1번 행
# 위에서 idx=1 넣었을 때 나온 vectors[0]이랑 같은지 비교

Parameter containing:
tensor([[-1.1258, -1.1524, -0.2506, -0.4339],
        [ 0.8487,  0.6920, -0.3160, -2.1152],
        [ 0.3223, -1.2633,  0.3500,  0.3081],
        [ 0.1198,  1.2377,  1.1168, -0.2473],
        [-1.3527, -1.6959,  0.5667,  0.7935],
        [ 0.5988, -1.5551, -0.3414,  1.8530],
        [-0.2159, -0.7425,  0.5627,  0.2596],
        [-0.1740, -0.6787,  0.9383,  0.4889],
        [ 1.2032,  0.0845, -1.2001, -0.0048],
        [-0.5181, -0.3067, -1.5810,  1.7066]], requires_grad=True)
tensor([ 0.8487,  0.6920, -0.3160, -2.1152], grad_fn=<SelectBackward0>)


In [3]:
optimizer = torch.optim.SGD(embedding.parameters(), lr=0.1)
target = torch.zeros(embed_dim)   # 1번 단어를 0벡터로 만들어보자

print("before:", embedding.weight[1])
for step in range(100):
    optimizer.zero_grad()
    vec = embedding(torch.tensor([1]))      # 1번 단어 벡터
    loss = ((vec - target) ** 2).mean()     # 목표와의 거리
    loss.backward()
    optimizer.step()
print("after:", embedding.weight[1])        # 0에 가까워졌나?

before: tensor([ 0.8487,  0.6920, -0.3160, -2.1152], grad_fn=<SelectBackward0>)
after: tensor([ 0.0050,  0.0041, -0.0019, -0.0125], grad_fn=<SelectBackward0>)
