In [1]:
import torch

In [14]:
a = torch.tensor([[1,2,3,4,5],[6,7,8,9,0]])
b = torch.zeros(2,5)
c = torch.ones(2,5)
d = torch.randn(5,2)
e= torch.randn(2,5)


In [15]:
tensors = [a,b,c,d]
for tensor in tensors:
    print(tensor.shape)
    print(tensor.dtype)

torch.Size([2, 5])
torch.int64
torch.Size([2, 5])
torch.float32
torch.Size([2, 5])
torch.float32
torch.Size([5, 2])
torch.float32


In [20]:
print(a+e)
print(a*e)
print(d@e)
print(d.matmul(e))

tensor([[ 1.0701,  2.4924,  3.3609,  3.8205,  5.8267],
        [ 5.5237,  7.5929,  7.8159,  8.8004, -0.8080]])
tensor([[ 0.0701,  0.9848,  1.0826, -0.7179,  4.1334],
        [-2.8581,  4.1500, -1.4728, -1.7962, -0.0000]])
tensor([[-1.0866,  0.9260, -0.6654, -0.3017, -2.3637],
        [-0.2588,  0.7772,  0.1620, -0.2724,  0.1167],
        [ 0.0802,  0.2895,  0.2552, -0.1067,  0.6116],
        [-0.2077,  0.0315, -0.2110, -0.0052, -0.6294],
        [ 0.0783, -0.0371,  0.0650,  0.0111,  0.2064]])
tensor([[-1.0866,  0.9260, -0.6654, -0.3017, -2.3637],
        [-0.2588,  0.7772,  0.1620, -0.2724,  0.1167],
        [ 0.0802,  0.2895,  0.2552, -0.1067,  0.6116],
        [-0.2077,  0.0315, -0.2110, -0.0052, -0.6294],
        [ 0.0783, -0.0371,  0.0650,  0.0111,  0.2064]])


In [24]:
a.numpy()
import numpy as np
torch.from_numpy(np.array([1,2,3,4,5]))

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [34]:
print(a.view(10))
e = e.reshape(5,2)
e.shape

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])


torch.Size([5, 2])

In [35]:
import torch

x = torch.tensor(3.0, requires_grad=True)
y = x ** 2  # y = x²
y.backward()  # 미분 실행
print(x.grad)  # dy/dx = 2x = 6.0

tensor(6.)


In [37]:
import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)  # 입력 1개, 출력 1개
    
    def forward(self, x):
        return self.linear(x)
    
model = MyModel()
print(model)
print(list(model.parameters()))

MyModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)
[Parameter containing:
tensor([[0.9485]], requires_grad=True), Parameter containing:
tensor([0.2730], requires_grad=True)]


In [38]:
x_train = torch.tensor([[1.0],[2.0],[3.0],[4.0]])
y_train = torch.tensor([[3.0],[5.0],[7.0],[9.0]])  # y = 2x + 1

# 모델, 손실함수, 옵티마이저
model = MyModel()
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [46]:
for i in range(1000):
    optimizer.zero_grad()
    y_pred = model(x_train)
    loss = criterion(y_pred,y_train)
    loss.backward()
    optimizer.step()
print(loss)

tensor(5.8852e-06, grad_fn=<MseLossBackward0>)


In [47]:
list(model.parameters())

[Parameter containing:
 tensor([[1.9980]], requires_grad=True),
 Parameter containing:
 tensor([1.0059], requires_grad=True)]

오늘 배운 거 정리:

Autograd: requires_grad=True → .backward() → .grad로 자동 미분
nn.Module: class로 모델 구조 정의 (레이어 + forward)
학습 루프 5줄: zero_grad → 예측 → loss → backward → step

이 5줄이 딥러닝 학습의 전부야. 앞으로 모델이 복잡해져도 이 구조는 똑같아.
오늘 push 해